### ISSUE TITLE
Let's make it official

### ISSUE THREAD

**Issue by razvanphp** [PeerMeHQ/mx-sdk-php#2]
Hey @michavie 

I was talking during xDay with @andreibancioiu and we were wondering if you would agree to move your SDK to the official MultiversX account, updating it according to the new [spec](https://github.com/multiversx/mx-sdk-specs) and keep maintaining it there together with the team, as official PHP SDK 🙂 

Thank you for your contribution!
R

**Comment by michavie** [comment]
Sounds great, let's do it!

Note that there are 3 SDKs related 2 PHP:

1. This one
2. Network Providers: https://github.com/PeerMeHQ/mx-sdk-php-network-providers
3. Laravel (most popular framework) Adapter: https://github.com/PeerMeHQ/mx-sdk-laravel

You can reach me on Telegram via `@michavie` for details of the transfer.

**Comment by andreibancioiu** [comment]
Hello @razvanphp, hello @michavie! 

At that point, I did not realize we were talking about @michavie's repositories :)

Updating according to specs is not a hard requirement, of course, and we should only consider it after some time, once other libraries are already aligned. Furthermore, there was an internal discussion to actually merge `mx-sdk-py-(core|wallet|network-providers)` into a single repository (though the split will remain for `sdk-js`, at least for now). Thus, if desired on you side, a merge of (1) and (2) is a perfectly valid choice.

Thank you so much for your contributions in the ecosystem :pray: 

We'll open the discussion separately.

**Comment by michavie** [comment]
Thank you for bringing it up, @razvanphp 

This is now in progress – you can follow the migration here: https://github.com/multiversx/mx-sdk-php
